`timescale 1ns / 1ps
// emamba_top_synth.v — CẤU HÌNH SẴN cho model hiện tại (QAT, head=80)
// Sinh tự động bởi gen_synth.py. Shift Linear+SSM+gamma+gating+res derive từ calib.
module emamba_top_synth (
    input wire clk, input wire rst_n,
    input wire in_valid, output wire in_ready, input wire [2559:0] in_data,
    output wire out_valid, input wire out_ready, output wire [455:0] out_data,
    output wire busy);
    localparam W = "D:/DATN/eMamba_Accelerator/rtl_export/weights";
    emamba_top #(
        .HEAD_H(80),
        .PE_SHIFT(5), .PE_W_FILE({W, "/pe_weight.hex"}), .PE_B_FILE({W, "/pe_bias.hex"}),
        .B0_GAMMA_SHIFT(-1), .B0_UPPER_SHIFT(8), .B0_LOWER_SHIFT(8),
        .B0_CONV_SHIFT(7), .B0_DELTA_SHIFT(6), .B0_DT_IN_SHIFT(8), .B0_B_SHIFT(7),
        .B0_C_SHIFT(8), .B0_OUT_SHIFT(8), .B0_SSM_Y_SHIFT(12),
        .B0_SSM_DA_SHIFT(5), .B0_SSM_DB_SHIFT(7), .B0_SSM_DX_ALIGN(5),
        .B0_GATING_SHIFT(4), .B0_RES_SHIFT(0),
        .B0_RES_A_LSHIFT(0), .B0_RES_B_LSHIFT(0), .B0_RES_B_RSHIFT(0),
        .B0_GAMMA_FILE({W, "/b0_gamma.hex"}),
        .B0_BETA_FILE({W, "/b0_beta.hex"}),
        .B0_UPPER_W({W, "/b0_upper_weight.hex"}),
        .B0_UPPER_B({W, "/b0_upper_bias.hex"}),
        .B0_LOWER_W({W, "/b0_lower_weight.hex"}),
        .B0_LOWER_B({W, "/b0_lower_bias.hex"}),
        .B0_CONV_W({W, "/b0_conv_weight.hex"}),
        .B0_CONV_B({W, "/b0_conv_bias.hex"}),
        .B0_DELTA_W({W, "/b0_delta_weight.hex"}),
        .B0_DELTA_B({W, "/b0_delta_bias.hex"}),
        .B0_DT_IN_W({W, "/b0_dtin_weight.hex"}),
        .B0_DT_IN_B({W, "/b0_dtin_bias.hex"}),
        .B0_B_W({W, "/b0_Bproj_weight.hex"}),
        .B0_C_W({W, "/b0_Cproj_weight.hex"}),
        .B0_OUT_W({W, "/b0_outproj_weight.hex"}),
        .B0_OUT_B({W, "/b0_outproj_bias.hex"}),
        .B0_A_FILE({W, "/b0_A_log.hex"}),
        .B0_D_FILE({W, "/b0_D_param.hex"}),
        .B0_SILU_LUT({W, "/siluG_b0"}),
        .B0_CONV_SILU_LUT({W, "/siluC_b0"}),
        .B1_GAMMA_SHIFT(-1), .B1_UPPER_SHIFT(8), .B1_LOWER_SHIFT(8),
        .B1_CONV_SHIFT(7), .B1_DELTA_SHIFT(7), .B1_DT_IN_SHIFT(7), .B1_B_SHIFT(6),
        .B1_C_SHIFT(7), .B1_OUT_SHIFT(7), .B1_SSM_Y_SHIFT(12),
        .B1_SSM_DA_SHIFT(5), .B1_SSM_DB_SHIFT(5), .B1_SSM_DX_ALIGN(3),
        .B1_GATING_SHIFT(4), .B1_RES_SHIFT(0),
        .B1_RES_A_LSHIFT(0), .B1_RES_B_LSHIFT(0), .B1_RES_B_RSHIFT(1),
        .B1_GAMMA_FILE({W, "/b1_gamma.hex"}),
        .B1_BETA_FILE({W, "/b1_beta.hex"}),
        .B1_UPPER_W({W, "/b1_upper_weight.hex"}),
        .B1_UPPER_B({W, "/b1_upper_bias.hex"}),
        .B1_LOWER_W({W, "/b1_lower_weight.hex"}),
        .B1_LOWER_B({W, "/b1_lower_bias.hex"}),
        .B1_CONV_W({W, "/b1_conv_weight.hex"}),
        .B1_CONV_B({W, "/b1_conv_bias.hex"}),
        .B1_DELTA_W({W, "/b1_delta_weight.hex"}),
        .B1_DELTA_B({W, "/b1_delta_bias.hex"}),
        .B1_DT_IN_W({W, "/b1_dtin_weight.hex"}),
        .B1_DT_IN_B({W, "/b1_dtin_bias.hex"}),
        .B1_B_W({W, "/b1_Bproj_weight.hex"}),
        .B1_C_W({W, "/b1_Cproj_weight.hex"}),
        .B1_OUT_W({W, "/b1_outproj_weight.hex"}),
        .B1_OUT_B({W, "/b1_outproj_bias.hex"}),
        .B1_A_FILE({W, "/b1_A_log.hex"}),
        .B1_D_FILE({W, "/b1_D_param.hex"}),
        .B1_SILU_LUT({W, "/siluG_b1"}),
        .B1_CONV_SILU_LUT({W, "/siluC_b1"}),
        .EXP_BP_FILE({W, "/exp_bp.hex"}), .EXP_SL_FILE({W, "/exp_sl.hex"}), .EXP_IC_FILE({W, "/exp_ic.hex"}),
        .HD_FFN_IN_SHIFT(7), .HD_FFN_OUT_SHIFT(5), .HD_PROJ_SHIFT(8),
        .HD_RES_B_LSHIFT(1), .HD_RES_B_RSHIFT(0),
        .HD_FFN_IN_W({W, "/head_ffn_in_weight.hex"}), .HD_FFN_IN_B({W, "/head_ffn_in_bias.hex"}),
        .HD_FFN_OUT_W({W, "/head_ffn_out_weight.hex"}), .HD_FFN_OUT_B({W, "/head_ffn_out_bias.hex"}),
        .HD_PROJ_W({W, "/head_proj_weight.hex"}), .HD_PROJ_B({W, "/head_proj_bias.hex"})
    ) u_core (
        .clk(clk), .rst_n(rst_n),
        .in_valid(in_valid), .in_ready(in_ready), .in_data(in_data),
        .out_valid(out_valid), .out_ready(out_ready), .out_data(out_data), .busy(busy),
        .wbus(16'd0), .use_shift_ovr(1'b0), .shift_ovr_b0(90'd0), .shift_ovr_b1(90'd0));
endmodule
